# Generated by Django 2.1.2 on 2018-10-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.TextField(max_length=1000, verbose_name='graph structure')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('eid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('eid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_group', to='contenttypes.ContentType', verbose_name='parent type')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_children', to='main.ParentItem', verbose_name='parent objects'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_children', to='main.ParentItem', verbose_name='parent objects'),
        ),
        migrations.AddField(
            model_name='graph',
            name='contained_groups',
            field=models.ManyToManyField(to='main.Group'),
        ),
        migrations.AddField(
            model_name='graph',
            name='contained_nodes',
            field=models.ManyToManyField(to='main.Node'),
        ),
    ]
