# Generated by Django 2.1.2 on 2018-10-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.TextField(blank=True, max_length=1000, null=True, verbose_name='graph structure')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('eid', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='main.Group', verbose_name='parent objects')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('eid', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='main.Group', verbose_name='parent objects')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='contained_groups',
            field=models.ManyToManyField(related_name='graph', to='main.Group'),
        ),
        migrations.AddField(
            model_name='graph',
            name='contained_nodes',
            field=models.ManyToManyField(related_name='graph', to='main.Node'),
        ),
    ]
